//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartaEvento
    {
        public string IdCarta { get; set; }
        public string estado { get; set; }
        public string robarCarta { get; set; }
        public string IdjugadorARobar { get; set; }
        public string retirar { get; set; }
    }
}
