//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesGloom : DbContext
    {
        public EntidadesGloom()
            : base("name=EntidadesGloom")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amigos> Amigos { get; set; }
        public virtual DbSet<CartaEvento> CartaEvento { get; set; }
        public virtual DbSet<CartaFamiliar> CartaFamiliar { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<Modificador> Modificador { get; set; }
        public virtual DbSet<Muerte> Muerte { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
    }
}
