//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public string IdSala { get; set; }
        public string NombreSala { get; set; }
        public string TipoSala { get; set; }
        public string TipoPartida { get; set; }
        public int NoJugadores { get; set; }
        public string Codigo { get; set; }
        public string IdAdministrador { get; set; }
        public string Fecha { get; set; }
        public string Ganador { get; set; }
    }
}
